### ISSUE TITLE
Undefined function causes error when using mobile Safari user agent

### ISSUE THREAD

**Issue by stevenbuccini** [kyle-jennings/franklin#6]
Attempting to load a Wordpress page with the Benjamin theme and the Franklin plugin installed causes an error. The issue appears to be that `benjamin_get_cpts()` in `columns.php` is undefined. Stack trace below.
```
[19-Oct-2019 11:19:23 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/htdocs/wp-content/themes/benjamin/inc/shared/widgets.php on line 35
[19-Oct-2019 11:19:48 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function benjamin_get_cpts() in /srv/htdocs/wp-content/plugins/franklin/inc/columns.php:53
Stack trace:
#0 /wordpress/core/5.2.4/wp-includes/class-wp-hook.php(286): benjamin_manage_columns('')
#1 /wordpress/core/5.2.4/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.2.4/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /wordpress/core/5.2.4/wp-settings.php(525): do_action('init')
#4 /srv/htdocs/wp-config.php(81): require_once('/wordpress/core...')
#5 /wordpress/core/5.2.4/wp-load.php(42): require_once('/srv/htdocs/wp-...')
#6 /wordpress/core/5.2.4/wp-blog-header.php(13): require_once('/wordpress/core...')
#7 /wordpress/core/5.2.4/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /srv/htdocs/wp-content/plugins/franklin/inc/columns.php on line 53
[19-Oct-2019 11:19:53 UTC] PHP Warning:  file_get_contents(/wordpress/core/5.2.4/wp-config.php): failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/enable-wp-debug-from-admin-dashboard/index.php on line 84
[19-Oct-2019 11:19:53 UTC] PHP Warning:  file_put_contents(/wordpress/core/5.2.4/wp-config.php): failed to open stream: Read-only file system in /srv/htdocs/wp-content/plugins/enable-wp-debug-from-admin-dashboard/index.php on line 110
[19-Oct-2019 11:20:01 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/htdocs/wp-content/themes/benjamin/inc/shared/widgets.php on line 35
```

**Comment by kyle-jennings** [comment]
Can you describe the conditions for this error in a little bit more detail. Specifically:

- Is this "WordPress page" a page on the front end,  or a post, or is it a custom post type page/post?
- The page/post in question, what was in the content? a columns shortcode or did the page use a template which included a horizontal sidebar?
- Did you download Franklin / Benjamin from Github or from the WordPress repo?

**Comment by stevenbuccini** [comment]
* The "WordPress page" is the standard WordPress error page that happens when you get a 500. It says something like "This site is experimenting technical difficulties."

* This occurred for both a home page and a custom page we were using (one of the `template1.php` pages included in the Benjamin theme. I believe both of these pages use a horizontal sidebar.

* I downloaded Benjamin off of GH because we were modifying it and uploading it back to WP as a zip. Franklin we downloaded through the WP package manager.
